
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Sun May 08 21:48:09 CEST 2022
//----------------------------------------------------

package c_ast_ascendente;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int LLCIERRE = 36;
  public static final int POR = 5;
  public static final int CCIERRE = 19;
  public static final int PCIERRE = 17;
  public static final int LIT_REAL = 58;
  public static final int LIT_CAD = 59;
  public static final int CAP = 18;
  public static final int INT = 38;
  public static final int ARRAY = 32;
  public static final int WRITE = 53;
  public static final int DELETE = 51;
  public static final int NOT = 8;
  public static final int AND = 7;
  public static final int IGUAL = 14;
  public static final int RECORD = 34;
  public static final int LLAP = 35;
  public static final int TYPE = 25;
  public static final int OR = 9;
  public static final int BOOL = 39;
  public static final int CALL = 54;
  public static final int DIGUAL = 55;
  public static final int DIV = 4;
  public static final int DAMP = 22;
  public static final int IF = 42;
  public static final int ID = 56;
  public static final int ENDWHILE = 48;
  public static final int OF = 33;
  public static final int EOF = 0;
  public static final int AMP = 28;
  public static final int TRUE = 29;
  public static final int NEW = 52;
  public static final int error = 1;
  public static final int LIT_ENT = 57;
  public static final int COMA = 27;
  public static final int PERCENT = 6;
  public static final int DIF = 15;
  public static final int MENOS = 3;
  public static final int NULL = 31;
  public static final int MENOR = 10;
  public static final int PCOMA = 23;
  public static final int REAL = 40;
  public static final int MAYOR = 11;
  public static final int PAP = 16;
  public static final int FLECHA = 21;
  public static final int ENDIF = 46;
  public static final int ELSE = 44;
  public static final int PUNTO = 20;
  public static final int NL = 50;
  public static final int READ = 49;
  public static final int WHILE = 45;
  public static final int MAYOR_IGUAL = 13;
  public static final int THEN = 43;
  public static final int STRING = 41;
  public static final int PROC = 26;
  public static final int MENOR_IGUAL = 12;
  public static final int POINTER = 37;
  public static final int FALSE = 30;
  public static final int VAR = 24;
  public static final int DO = 47;
  public static final int MAS = 2;
}

