package implementacion_manual;

public enum ClaseLexica {
	
	SEP, SEP_PC, ASIG, FALSE, TRUE, MAS, MENOS, POR, DIV, AND, OR, NOT, MENOR, MAYOR, MENOR_IGUAL, MAYOR_IGUAL, IGUAL,
	DIF, PAP, PCIERRE, PUNTO, COMA, VAR, NUM_ENT, NUM_REAL, PDEC, PEXP

}
