/* Generated By:JavaCC: Do not edit this line. ConstructorASTConstants.java */
package c_ast_descendente;

public interface ConstructorASTConstants {

  int EOF = 0;
  int letra = 1;
  int digitoPositivo = 2;
  int digito = 3;
  int parteEntera = 4;
  int parteDecimal = 5;
  int parteExponencial = 6;
  int signo = 7;
  int AND = 10;
  int OR = 11;
  int NOT = 12;
  int FALSE = 13;
  int TRUE = 14;
  int INT = 15;
  int REAL = 16;
  int STRING = 17;
  int BOOL = 18;
  int NULL = 19;
  int PROC = 20;
  int IF = 21;
  int THEN = 22;
  int ELSE = 23;
  int ENDIF = 24;
  int WHILE = 25;
  int DO = 26;
  int ENDWHILE = 27;
  int CALL = 28;
  int RECORD = 29;
  int ARRAY = 30;
  int OF = 31;
  int POINTER = 32;
  int NEW = 33;
  int DELETE = 34;
  int READ = 35;
  int WRITE = 36;
  int NL = 37;
  int VAR = 38;
  int TYPE = 39;
  int comillas = 40;
  int litCad = 41;
  int identificador = 42;
  int litEnt = 43;
  int litReal = 44;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<letra>",
    "<digitoPositivo>",
    "<digito>",
    "<parteEntera>",
    "<parteDecimal>",
    "<parteExponencial>",
    "<signo>",
    "<token of kind 8>",
    "<token of kind 9>",
    "\"and\"",
    "\"or\"",
    "\"not\"",
    "\"false\"",
    "\"true\"",
    "\"int\"",
    "\"real\"",
    "\"string\"",
    "\"bool\"",
    "\"null\"",
    "\"proc\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"endif\"",
    "\"while\"",
    "\"do\"",
    "\"endwhile\"",
    "\"call\"",
    "\"record\"",
    "\"array\"",
    "\"of\"",
    "\"pointer\"",
    "\"new\"",
    "\"delete\"",
    "\"read\"",
    "\"write\"",
    "\"nl\"",
    "\"var\"",
    "\"type\"",
    "\"\\\"\"",
    "<litCad>",
    "<identificador>",
    "<litEnt>",
    "<litReal>",
    "\"&&\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"&\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\"=\"",
    "\"+\"",
    "\"-\"",
    "\".\"",
    "\"->\"",
    "\"*\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"==\"",
    "\"!=\"",
    "\"/\"",
    "\"%\"",
  };

}
