package implementacion_jflex;

public enum ClaseLexica {

	ID, LIT_ENT, LIT_REAL, LIT_CAD, AMP, DAMP, MAS, MENOS, POR, DIV, PORCENT, MENOR, MAYOR, MENOR_IGUAL, MAYOR_IGUAL, 
	IGUAL, DIGUAL, DIF, PAP, PCIERRE, CAP, CCIERRE, LLAP, LLCIERRE, PUNTO, COMA, PCOMA, FLECHA, EOF,
	
	INT, REAL, BOOL, STRING, AND, OR, NOT, NULL, TRUE, FALSE, PROC, IF, THEN, ELSE, ENDIF, WHILE, DO, ENDWHILE, 
	CALL, RECORD, ARRAY, OF, POINTER, NEW, 	DELETE, READ, WRITE, NL, VAR, TYPE

}
