package alex;

public enum ClaseLexica {
	
	DAMP, PCOMA, IGUAL, FALSE, TRUE, MAS, MENOS, POR, DIV, AND, OR, NOT, MENOR, MAYOR, MENOR_IGUAL, MAYOR_IGUAL, DIGUAL,
	DIF, PAP, PCIERRE, PUNTO, ID, NUM_ENT, NUM_REAL, PDEC, PEXP, EOF

}
