
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Sun Mar 27 14:13:39 CEST 2022
//----------------------------------------------------

package asint;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int DISTINTO = 15;
  public static final int LLCIERRE = 40;
  public static final int POR = 5;
  public static final int CCIERRE = 19;
  public static final int PCIERRE = 17;
  public static final int LIT_REAL = 33;
  public static final int CAP = 18;
  public static final int LIT_CAD = 34;
  public static final int INT = 42;
  public static final int ARRAY = 36;
  public static final int WRITE = 57;
  public static final int DELETE = 55;
  public static final int NOT = 8;
  public static final int AND = 7;
  public static final int IGUAL = 14;
  public static final int RECORD = 38;
  public static final int LLAP = 39;
  public static final int TYPE = 26;
  public static final int OR = 9;
  public static final int BOOL = 43;
  public static final int CALL = 58;
  public static final int DIGUAL = 59;
  public static final int DIV = 4;
  public static final int DAMP = 22;
  public static final int IF = 46;
  public static final int ENDWHILE = 52;
  public static final int ID = 25;
  public static final int OF = 37;
  public static final int EOF = 0;
  public static final int AMP = 29;
  public static final int TRUE = 30;
  public static final int NEW = 56;
  public static final int error = 1;
  public static final int COMA = 28;
  public static final int LIT_ENT = 32;
  public static final int PERCENT = 6;
  public static final int MENOS = 3;
  public static final int NULL = 35;
  public static final int MENOR = 10;
  public static final int PCOMA = 23;
  public static final int MENIG = 12;
  public static final int REAL = 44;
  public static final int MAYOR = 11;
  public static final int PAP = 16;
  public static final int FLECHA = 21;
  public static final int ENDIF = 50;
  public static final int ELSE = 48;
  public static final int PUNTO = 20;
  public static final int MAYIG = 13;
  public static final int NL = 54;
  public static final int READ = 53;
  public static final int WHILE = 49;
  public static final int THEN = 47;
  public static final int STRING = 45;
  public static final int PROC = 27;
  public static final int POINTER = 41;
  public static final int FALSE = 31;
  public static final int VAR = 24;
  public static final int DO = 51;
  public static final int MAS = 2;
}

