package alex;

public enum ClaseLexica {

	ID, LIT_ENT, LIT_REAL, LIT_CAD, DAMP, MAS, MENOS, POR, DIV, PORCENT, MENOR, MAYOR, MENOR_IGUAL, MAYOR_IGUAL, DIGUAL, 
	DIF, PAP, PCIERRE, PCOMA, IGUAL, CAP, CCIERRE, LLAP, LLCIERRE, PUNTO, FLECHA, COMA, AMP, EOF,
	
	INT, REAL, BOOL, STRING, AND, OR, NOT, NULL, TRUE, FALSE, PROC, IF, THEN, ELSE, ENDIF, WHILE, DO, ENDWHILE, 
	CALL, RECORD, ARRAY, OF, POINTER, NEW, 	DELETE, READ, WRITE, NL, VAR, TYPE

}
